cmake_minimum_required(VERSION 3.16)
project(xlang)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -g -O0 -Wall -pedantic -Werror")

add_library(
    nodes
    top/Alias.cpp
    top/Alias.h
    statements/Assignment.cpp
    statements/Assignment.h
    ast.h
    statements/Block.cpp
    statements/Block.h
    statements/Break.cpp
    statements/Break.h
    statements/Call.cpp
    statements/Call.h
    expressions/src/Cast.cpp
    expressions/Cast.h
    statements/Continue.cpp
    statements/Continue.h
    statements/Declaration.cpp
    statements/Declaration.h
    expressions/src/BinaryOp.cpp
    expressions/include/BinaryOp.h
    expressions/src/Boolean.cpp
    expressions/include/Boolean.h
    expressions/src/CallExp.cpp
    expressions/include/CallExp.h
    expressions/src/DefaultConstructor.cpp
    expressions/include/DefaultConstructor.h
    expressions/include/DefaultConstructor.h
    expressions/src/DictNode.cpp
    expressions/include/DictNode.h
    expressions/src/EmptyDict.cpp
    expressions/include/EmptyDict.h
    expressions/src/EmptyList.cpp
    expressions/include/EmptyList.h
    expressions/src/ExpNode.cpp
    expressions/include/ExpNode.h
    expressions/src/Id.cpp
    expressions/include/Id.h
    expressions/src/List.cpp
    expressions/include/List.h
    expressions/src/Member.cpp
    expressions/include/Member.h
    expressions/src/None.cpp
    expressions/include/None.h
    expressions/src/Number.cpp
    expressions/include/Number.h
    expressions/src/PartialApplication.cpp
    expressions/include/PartialApplication.h
    expressions/src/String.cpp
    expressions/include/String.h
    expressions/src/Subscript.cpp
    expressions/include/Subscript.h
    expressions/src/Ternary.cpp
    expressions/include/Ternary.h
    expressions/src/Tuple.cpp
    expressions/include/Tuple.h
    expressions/src/UnaryOp.cpp
    expressions/include/UnaryOp.h
    statements/For.cpp
    statements/For.h
    general/FunctionType.cpp
    general/TypeFunction.h
    statements/If.cpp
    statements/If.h
    top/Import.cpp
    top/Import.h
    top/Instance.cpp
    top/Instance.h
    statements/Match.cpp
    statements/Match.h
    statements/Statement.cpp
    statements/Statement.cpp
    statements/Statement.h
    statements/Statement.h
    nodes.h
    general/ObjectType.cpp
    general/ObjectType.h
    optypes.cpp
    optypes.h
    ../util/Path.cpp
    ../util/Path.h
    statements/Return.cpp
    statements/Return.h
    top/EnumNode.cpp
    top/EnumNode.h
    top/Function.cpp
    top/Function.h
    top/Klass.cpp
    top/Klass.h
    top/Module.cpp
    top/Module.h
    top/TopNode.cpp
    top/TopNode.h
    general/Type.h
    top/Typeclass.cpp
    top/Typeclass.h
    general/TypeNode.cpp
    statements/While.cpp
    statements/While.h
)
