cmake_minimum_required(VERSION 3.16)
project(xlang)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -g -O0 -Wall -pedantic -Werror")

add_library(
        nodes
        AliasNode.cpp
        AliasNode.h
        Assignment.cpp
        Assignment.h
        Binop.cpp
        Binop.h
        Block.cpp
        Block.h
        Boolean.cpp
        Boolean.h
        BoolOpNode.cpp
        BoolOpNode.h
        BreakNode.cpp
        BreakNode.h
        Call.cpp
        Call.h
        CastNode.cpp
        CastNode.h
        Klass.cpp
        Klass.h
        ContinueNode.cpp
        ContinueNode.h
        Declaration.cpp
        Declaration.h
        DefaultConstructorNode.cpp
        DefaultConstructorNode.h
        DefaultConstructorNode.h
        DictNode.cpp
        DictNode.h
        EmptyDictNode.cpp
        EmptyDictNode.h
        EmptyListNode.cpp
        EmptyListNode.h
        EnumNode.cpp
        EnumNode.h
        For.cpp
        For.h
        Function.cpp
        Function.h
        Id.cpp
        Id.h
        If.cpp
        If.h
        ImportNode.cpp
        ImportNode.h
        InstanceNode.cpp
        InstanceNode.h
        ListNode.cpp
        ListNode.h
        MatchExpressionNode.cpp
        MatchExpressionNode.h
        Member.cpp
        Member.h
        Node.cpp
        Node.cpp
        Node.h
        Node.h
        nodes.h
        NoneNode.cpp
        NoneNode.h
        NumberNode.cpp
        NumberNode.h
        optypes.cpp
        optypes.h
        PartialApplication.cpp
        PartialApplication.h
        Return.cpp
        Return.h
        String.cpp
        String.h
        SubscriptNode.cpp
        SubscriptNode.h
        TernaryNode.cpp
        TernaryNode.h
        TryCatchNode.cpp
        TryCatchNode.h
        TupleNode.cpp
        TupleNode.h
        TypeNode.cpp
        TypeNode.h
        TypeclassNode.cpp
        TypeclassNode.h
        UnaryOpNode.cpp
        UnaryOpNode.h
        While.cpp
        While.h ObjectType.cpp ObjectType.h FunctionType.cpp FunctionType.h Path.cpp Path.h ast.h)

target_precompile_headers(nodes PUBLIC ../json/json.hpp)
