cmake_minimum_required(VERSION 3.16)
project(xlang)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -g -O0 -Wall -pedantic -Werror")

add_library(
    nodes
    Alias.cpp
    Alias.h
    Assignment.cpp
    Assignment.h
    ast.h
    Block.cpp
    Block.h
    Break.cpp
    Break.h
    Call.cpp
    Call.h
    Cast.cpp
    Cast.h
    Continue.cpp
    Continue.h
    Declaration.cpp
    Declaration.h
    exp/src/BinaryOp.cpp
    exp/include/BinaryOp.h
    exp/src/Boolean.cpp
    exp/include/Boolean.h
    exp/src/CallExp.cpp
    exp/include/CallExp.h
    exp/src/DefaultConstructor.cpp
    exp/include/DefaultConstructor.h
    exp/include/DefaultConstructor.h
    exp/src/DictNode.cpp
    exp/include/DictNode.h
    exp/src/EmptyDict.cpp
    exp/include/EmptyDict.h
    exp/src/EmptyList.cpp
    exp/include/EmptyList.h
    exp/src/ExpNode.cpp
    exp/include/ExpNode.h
    exp/src/Id.cpp
    exp/include/Id.h
    exp/src/List.cpp
    exp/include/List.h
    exp/src/Member.cpp
    exp/include/Member.h
    exp/src/None.cpp
    exp/include/None.h
    exp/src/Number.cpp
    exp/include/Number.h
    exp/src/PartialApplication.cpp
    exp/include/PartialApplication.h
    exp/src/String.cpp
    exp/include/String.h
    exp/src/Subscript.cpp
    exp/include/Subscript.h
    exp/src/Ternary.cpp
    exp/include/Ternary.h
    exp/src/Tuple.cpp
    exp/include/Tuple.h
    exp/src/UnaryOp.cpp
    exp/include/UnaryOp.h
    For.cpp
    For.h
    FunctionType.cpp
    FunctionType.h
    If.cpp
    If.h
    Import.cpp
    Import.h
    Instance.cpp
    Instance.h
    Match.cpp
    Match.h
    Node.cpp
    Node.cpp
    Node.h
    Node.h
    nodes.h
    ObjectType.cpp
    ObjectType.h
    optypes.cpp
    optypes.h
    Path.cpp
    Path.h
    Return.cpp
    Return.h
    top/EnumNode.cpp
    top/EnumNode.h
    top/Function.cpp
    top/Function.h
    top/Klass.cpp
    top/Klass.h
    top/Module.cpp
    top/Module.h
    top/TopNode.cpp
    top/TopNode.h
    Type.h
    Typeclass.cpp
    Typeclass.h
    TypeNode.cpp
    While.cpp
    While.h
)
