cmake_minimum_required(VERSION 3.16)
project(xlang)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -g -O0 -Wall -pedantic -Werror")

add_library(
        nodes
        AliasNode.cpp
        AliasNode.h
        AssignmentNode.cpp
        AssignmentNode.h
        BinopNode.cpp
        BinopNode.h
        BlockNode.cpp
        BlockNode.h
        BooleanNode.cpp
        BooleanNode.h
        BoolOpNode.cpp
        BoolOpNode.h
        BreakNode.cpp
        BreakNode.h
        CallNode.cpp
        CallNode.h
        CastNode.cpp
        CastNode.h
        ClassNode.cpp
        ClassNode.h
        ContinueNode.cpp
        ContinueNode.h
        DeclarationNode.cpp
        DeclarationNode.h
        DefaultConstructorNode.cpp
        DefaultConstructorNode.h
        DefaultConstructorNode.h
        DictNode.cpp
        DictNode.h
        EmptyDictNode.cpp
        EmptyDictNode.h
        EmptyListNode.cpp
        EmptyListNode.h
        EnumNode.cpp
        EnumNode.h
        ForNode.cpp
        ForNode.h
        FunctionNode.cpp
        FunctionNode.h
        IdNode.cpp
        IdNode.h
        IfNode.cpp
        IfNode.h
        ImportNode.cpp
        ImportNode.h
        ListNode.cpp
        ListNode.h
        MatchExpressionNode.cpp
        MatchExpressionNode.h
        MemberNode.cpp
        MemberNode.h
        MethodNode.cpp
        MethodNode.h
        Node.cpp
        Node.cpp
        Node.h
        Node.h
        nodes.h
        NoneNode.cpp
        NoneNode.h
        NumberNode.cpp
        NumberNode.h
        optypes.cpp
        optypes.h
        PartialApplication.cpp
        PartialApplication.h
        ReturnNode.cpp
        ReturnNode.h
        StringNode.cpp
        StringNode.h
        SubscriptNode.cpp
        SubscriptNode.h
        TernaryNode.cpp
        TernaryNode.h
        ThrowNode.cpp
        ThrowNode.h
        TryCatchNode.cpp
        TryCatchNode.h
        TupleNode.cpp
        TupleNode.h
        TypeNode.cpp
        TypeNode.h
        UnaryOpNode.cpp
        UnaryOpNode.h
        WhileNode.cpp
        WhileNode.h ObjectType.cpp ObjectType.h FunctionType.cpp FunctionType.h Path.cpp Path.h)

target_precompile_headers(nodes PUBLIC ../json/json.hpp)
