cmake_minimum_required(VERSION 3.16)
project(xlang)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -g -O0 -Wall -pedantic -Werror")

add_library(
    semantic
    ../util/macros.h
    ../util/types.h
    ../util/utils.cpp
    ../util/utils.h
    CheckCall.cpp
    CheckCall.h
    CheckDeclaration.cpp
    CheckDeclaration.h
    Checker.cpp
    Checker.h
    CheckerUnify.cpp
    CheckerUtils.cpp
    CheckerUtils.h
    CheckerVisit.cpp
    CheckExpressions.cpp
    CheckExpressions.h
    CheckLiterals.cpp
    CheckLiterals.h
    CheckMember.cpp
    CheckMember.h
    CheckStatements.cpp
    CheckStatements.h
    errors/include/Error.h
    errors/include/ErrorBadReturn.h
    errors/include/ErrorBoolOp.h
    errors/include/ErrorCantAssign.h
    errors/include/ErrorClassNoMember.h
    errors/include/ErrorClassNoMethodForOp.h
    errors/include/ErrorEnumNoValue.h
    errors/include/ErrorExpectedExpression.h
    errors/include/ErrorFor.h
    errors/include/ErrorFunctionCallNumArgs.h
    errors/include/ErrorFunctionReturnLastStmt.h
    errors/include/ErrorListLiteral.h
    errors/include/ErrorNoMember.h
    errors/include/ErrorNoMemberSuggestions.h
    errors/include/ErrorNotAFunction.h
    errors/include/ErrorNotDeclared.h
    errors/include/ErrorObjectNoSpecialMethod.h
    errors/include/ErrorPackageNoMember.h
    errors/include/ErrorPartialWrongNumArgs.h
    errors/include/ErrorGlobalRedeclared.h
    errors/include/ErrorRedeclared.h
    errors/include/ErrorReporter.h
    errors/include/errors.h
    errors/include/ErrorTypeMismatch.h
    errors/include/ErrorUnusedReturnValue.h
    errors/src/Error.cpp
    errors/src/ErrorBadReturn.cpp
    errors/src/ErrorBoolOp.cpp
    errors/src/ErrorCantAssign.cpp
    errors/src/ErrorClassNoMember.cpp
    errors/src/ErrorClassNoMethodForOp.cpp
    errors/src/ErrorEnumNoValue.cpp
    errors/src/ErrorExpectedExpression.cpp
    errors/src/ErrorFor.cpp
    errors/src/ErrorFunctionCallNumArgs.cpp
    errors/src/ErrorFunctionReturnLastStmt.cpp
    errors/src/ErrorListLiteral.cpp
    errors/src/ErrorNoMember.cpp
    errors/src/ErrorNoMemberSuggestions.cpp
    errors/src/ErrorNotAFunction.cpp
    errors/src/ErrorNotDeclared.cpp
    errors/src/ErrorObjectNoSpecialMethod.cpp
    errors/src/ErrorPackageNoMember.cpp
    errors/src/ErrorPartialWrongNumArgs.cpp
    errors/src/ErrorRedeclared.cpp
    errors/src/ErrorGlobalRedeclared.cpp
    errors/src/ErrorReporter.cpp
    errors/src/ErrorTypeMismatch.cpp
    errors/src/ErrorUnusedReturnValue.cpp
    ExpressionInfo.cpp
    ExpressionInfo.h
    GlobalProcessor.cpp
    SymbolTable.cpp
    SymbolTable.h
    util.cpp
    util.h
)

target_link_libraries(semantic units simple_nodes)
