cmake_minimum_required(VERSION 3.16)
project(xlang)
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror -O0 -fverbose-asm -Winline")
include_directories(/home/chris/CLionProjects/compiler/runtime)
link_directories(/home/chris/CLionProjects/compiler/runtime/build)
add_subdirectory(runtime)
add_subdirectory(application)
target_link_libraries(result core)
