cmake_minimum_required(VERSION 3.16)
project(untitled1)

set(CMAKE_CXX_STANDARD 11)

add_library(srcLib
        scanner/Scanner.cpp
        scanner/Scanner.h
        scanner/Token.cpp
        scanner/Token.h
        color_codes.h
        parser/Parser.cpp
        parser/Parser.h
        semantic/ClassTable.cpp
        semantic/ClassTable.h
        semantic/SymbolTable.cpp
        semantic/SymbolTable.h
        nodes/Visitor.cpp
        nodes/Visitor.h
        nodes/ReturnNode.cpp
        nodes/ReturnNode.h
        nodes/StructNode.cpp
        nodes/StructNode.h
        nodes/StringNode.cpp
        nodes/StringNode.h
        nodes/BinopNode.cpp
        nodes/BinopNode.h
        nodes/Node.cpp
        nodes/Node.h
        nodes/MemberNode.cpp
        nodes/MemberNode.h
        nodes/ListNode.cpp
        nodes/ListNode.h
        nodes/SubscriptNode.cpp
        nodes/SubscriptNode.h
        nodes/nodes.h
        nodes/CallNode.cpp
        nodes/CallNode.h
        nodes/FunctionNode.cpp
        nodes/FunctionNode.h
        nodes/DeclarationNode.cpp
        nodes/DeclarationNode.h
        nodes/TypeNode.cpp
        nodes/TypeNode.h
        nodes/IfNode.cpp
        nodes/IfNode.h
        nodes/IdNode.cpp
        nodes/IdNode.h
        nodes/NumberNode.cpp
        nodes/NumberNode.h
        nodes/AssignmentNode.cpp
        nodes/AssignmentNode.h
        semantic/GlobalProcessor.cpp
        utils.h
        semantic/SymbolInfo.cpp
        semantic/SymbolInfo.h
        semantic/ObjectInfo.cpp
        semantic/ObjectInfo.h
        semantic/ClassInfo.cpp
        semantic/ClassInfo.h
        semantic/FunctionInfo.cpp
        semantic/FunctionInfo.h
        semantic/Checker.cpp
        semantic/Checker.h
        semantic/RedeclareError.cpp
        semantic/RedeclareError.h
        semantic/BadArguments.cpp
        semantic/BadArguments.h
        semantic/ReturnError.cpp
        semantic/ReturnError.h
        semantic/ScopeError.cpp
        semantic/ScopeError.h
        nodes/BlockNode.cpp
        nodes/BlockNode.h
        translator/Translator.cpp
        translator/Translator.h
        instructions/GetInst.cpp
        instructions/GetInst.h
        instructions/SetInst.cpp
        instructions/SetInst.h
        instructions/DeclareInst.cpp
        instructions/DeclareInst.h
        instructions/BinopInst.cpp
        instructions/BinopInst.h
        instructions/PushIntegerInst.cpp
        instructions/PushIntegerInst.h
        instructions/PushStringInst.cpp
        instructions/PushStringInst.h
        instructions/Instruction.cpp
        instructions/Instruction.h
        instructions/CallInst.cpp
        instructions/CallInst.h
        instructions/ReturnInst.cpp
        instructions/ReturnInst.h
        instructions/GetMemberInst.cpp
        instructions/GetMemberInst.h
        instructions/SetMemberInst.cpp
        instructions/SetMemberInst.h
        instructions/SetSubscriptInst.cpp
        instructions/SetSubscriptInst.h
        instructions/GetSubscriptInst.cpp
        instructions/GetSubscriptInst.h
        instructions/PushFunctionInst.cpp
        instructions/PushFunctionInst.h
        instructions/instructions.h
        instructions/InstructionVisitor.cpp
        instructions/InstructionVisitor.h
        vm/ObjectStack.h
        vm/ObjectStack.cpp
        vm/Object.h
        vm/Object.cpp
        vm/BuiltinSum.cpp
        vm/BuiltinSum.h
        vm/CodeObject.cpp
        vm/CodeObject.h
        vm/CodeUser.cpp
        vm/CodeUser.h
        vm/IntegerObject.cpp
        vm/IntegerObject.h
        vm/StringObject.cpp
        vm/StringObject.h
        vm/Environment.h
        vm/Environment.cpp
        vm/CodeRunner.h
        vm/CodeRunner.cpp
        vm/UserObject.cpp
        vm/UserObject.h
        instructions/MakeObjectInst.cpp
        instructions/MakeObjectInst.h
        instructions/MakeListInst.cpp
        instructions/MakeListInst.h 
        vm/ListObject.cpp
        vm/ListObject.h
        instructions/JumpIfFalseInst.cpp
        instructions/JumpIfFalseInst.h
        instructions/PushBooleanInst.cpp
        instructions/PushBooleanInst.h
        vm/BooleanObject.cpp
        vm/BooleanObject.h
        instructions/MakeClassInst.cpp
        instructions/MakeClassInst.h
        nodes/ClassLiteralExpressionNode.cpp
        nodes/ClassLiteralExpressionNode.h
        nodes/ClassLiteralFieldNode.cpp
        nodes/ClassLiteralFieldNode.h
        instructions/DefineStructInst.cpp
        instructions/DefineStructInst.h
        instructions/MakeDefaultInst.cpp
        instructions/MakeDefaultInst.h
        parser/UnexpectedToken.cpp
        parser/UnexpectedToken.h nodes/ForNode.cpp nodes/ForNode.h)