cmake_minimum_required(VERSION 3.16)
project(xlang)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -g -O0 -Wall -pedantic -Werror")

add_library(
        simple_nodes
        with_unique/Assignment.cpp
        with_unique/Assignment.h
        common/Block.cpp
        common/Block.h
        expressions/Bool.cpp
        expressions/Bool.h
        with_unique/Break.cpp
        with_unique/Break.h
        with_unique/Call.cpp
        with_unique/Call.h
        common/KlassDef.cpp
        common/KlassDef.h
        with_unique/Continue.cpp
        with_unique/Continue.h
        common/Declaration.cpp
        common/Declaration.h
        expressions/Dict.cpp
        expressions/Dict.h
        expressions/EnumMember.cpp
        expressions/EnumMember.h
        with_unique/EnumDef.cpp
        with_unique/EnumDef.h
        expressions/Float.cpp
        expressions/Float.h
        with_unique/FunctionDef.cpp
        with_unique/FunctionDef.cpp
        with_unique/FunctionDef.h
        with_unique/FunctionDef.h
        expressions/Id.cpp
        expressions/Id.h
        with_unique/IfSNode.cpp
        with_unique/IfSNode.h
        expressions/Integer.cpp
        expressions/Integer.h
        expressions/List.cpp
        expressions/List.h
        common/Match.cpp
        common/Match.h
        common/NewObject.cpp
        common/NewObject.h
        expressions/None.cpp
        expressions/None.h
        expressions/ObjectMember.cpp
        expressions/ObjectMember.h
        with_unique/Return.cpp
        with_unique/Return.h
        common/SNode.cpp
        common/SNode.h
        expressions/String.cpp
        expressions/String.h
        expressions/Ternary.cpp
        expressions/Ternary.h
        common/Throw.cpp
        common/Throw.h
        common/TryCatch.cpp
        common/TryCatch.h
        common/Type.cpp
        common/Type.h
        common/FunctionType.cpp
        common/TypeFunction.h
        common/TypeObject.h
        common/ObjectType.cpp
        with_unique/While.cpp
        common/sem.h
        with_unique/ObjectMethodCall.cpp
        with_unique/ObjectMethodCall.h
        expressions/ObjectMethod.cpp
        expressions/ObjectMethod.h
        with_unique/ConstFunctionCall.cpp
        with_unique/ConstFunctionCall.h
        with_unique/ConstFunction.cpp
        with_unique/ConstFunction.h
        expressions/ObjectConstructor.cpp
        expressions/ObjectConstructor.h
        expressions/ObjectConstructorCall.cpp
        expressions/ObjectConstructorCall.h
)
