cmake_minimum_required(VERSION 3.16)
project(xlang)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -g -O0 -Wall -pedantic -Werror")

add_library(
    simple_nodes
    common/src/Assignment.cpp
    common/include/Assignment.h
    common/src/Block.cpp
    common/include/Block.h
    expressions/src/Bool.cpp
    expressions/include/Bool.h
    common/src/Break.cpp
    common/include/Break.h
    common/src/Call.cpp
    common/include/Call.h
    common/src/KlassDef.cpp
    common/include/KlassDef.h
    common/src/Continue.cpp
    common/include/Continue.h
    common/src/Declaration.cpp
    common/include/Declaration.h
    expressions/src/Dict.cpp
    expressions/include/Dict.h
    expressions/src/EnumMember.cpp
    expressions/include/EnumMember.h
    common/src/EnumDef.cpp
    common/include/EnumDef.h
    expressions/src/Float.cpp
    expressions/include/Float.h
    common/src/FunctionDef.cpp
    common/src/FunctionDef.cpp
    common/include/FunctionDef.h
    common/include/FunctionDef.h
    expressions/src/Id.cpp
    expressions/include/Id.h
    common/src/IfSNode.cpp
    common/include/IfSNode.h
    expressions/src/Integer.cpp
    expressions/include/Integer.h
    expressions/src/List.cpp
    expressions/include/List.h
    common/src/Match.cpp
    common/include/Match.h
    expressions/src/NewObject.cpp
    expressions/include/NewObject.h
    expressions/src/None.cpp
    expressions/include/None.h
    expressions/src/ObjectMember.cpp
    expressions/include/ObjectMember.h
    common/src/Return.cpp
    common/include/Return.h
    common/src/SNode.cpp
    common/include/SNode.h
    expressions/src/String.cpp
    expressions/include/String.h
    expressions/src/CallExp.cpp
    expressions/include/CallExp.h
    expressions/src/Ternary.cpp
    expressions/include/Ternary.h
    common/src/Throw.cpp
    common/include/Throw.h
    common/src/TryCatch.cpp
    common/include/TryCatch.h
    common/src/Type.cpp
    common/include/Type.h
    common/src/FunctionType.cpp
    common/src/TypeFunction.h
    common/include/TypeObject.h
    common/src/ObjectType.cpp
    common/src/While.cpp
    sem.h
    expressions/src/ObjectMethod.cpp
    expressions/include/ObjectMethod.h
    expressions/src/ConstFunction.cpp
    expressions/include/ConstFunction.h
    expressions/src/ObjectConstructor.cpp
    expressions/include/ObjectConstructor.h
    expressions/src/ObjectConstructor.cpp
    expressions/include/ObjectConstructor.h
    expressions/src/Exp.cpp
    expressions/include/Exp.h
    expressions/include/expressions.h
    common/include/common.h)
